name: Build docker images and deploy

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Get version tag
        id: get_tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/bake-action@v6
        with:
          source: .
          push: 'true'
          no-cache: 'true'
          files: docker-bake.hcl

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build:prod

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${GITHUB_REF#refs/tags/}
          path: dist/mensarater/

  deploy:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-and-push-backend]
    steps:
      - name: Create Google service account key file and firebase config
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}' > service-account-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account-key.json
          mkdir firebase
          echo '${{ vars.FIREBASE_CONFIG }}' > firebase/firebase.json

      - name: Download frontend artifact
        uses: actions/download-artifact@v5
        with:
          name: frontend-build-${GITHUB_REF#refs/tags/}
          path: firebase

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: debug
        run: |
          cd firebase
          ls

      #- name: Deploy to Firebase
      #  run: firebase deploy --project mensarater
