name: Execute frontend and backend tests
on:
  pull_request:
    paths:
      - 'ui/**'
      - 'backend/**'

jobs:
  frontend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build:prod

      - name: Run linter
        run: npm run lint

      - name: Run frontend unit tests
        run: npm run test:unit

  backend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Make maven wrapper executable
        run: chmod +x mvnw

      - name: Build backend
        run: ./mvnw clean package

      - name: Run checkstyle
        run: ./mvnw checkstyle:check

      - name: Run unit tests
        run: ./mvnw clean test
